### ISSUE TITLE
Won't startup any games

### ISSUE THREAD

**Issue by MailBoxSNES** [MarioSilvaGH/Ninty-Launcher#2]
when i launched baldi after i got pass the discalmer screen but the closed out on me and avast blocked Ninty_Launcher.exe, i made it as an exception but now Ninty Launcher won't launch anymore games

**Comment by ninstar** [comment]
before extracting the launcher, 'unlock' the .zip by going to "properties" with the right mouse button, it's the last option (a checkbox) above the "apply" button. then try to start as administrator, if it does not solve the problem: if you have GameMaker Studio (1.4 or 2.0) you can compile an executable from the source code.
the first solution probably should work fine.

**Comment by GabrielGames990** [comment]
![image](https://user-images.githubusercontent.com/50301804/57970406-823f5f00-7970-11e9-9084-20f9d2be2fcd.png)
The Launcher Dosen't Open Any .url Archives
And Dosen't Work As Forwader

**Comment by ninstar** [comment]
> ![image](https://user-images.githubusercontent.com/50301804/57970406-823f5f00-7970-11e9-9084-20f9d2be2fcd.png)
> The Launcher Dosen't Open Any .url Archives
> And Dosen't Work As Forwader

This issue was fixed in 1.9.2, if you continue to experience it, try to put the launcher in a shorter directory.
